CIA-Homebrew/BJCP-Scoresheet

- controllers/ScoresheetController.js
- models/Scoresheet.js
- views/loadScoreSheetList.pug
- views/newScoresheet.pug
fixed issue with existing scoresheets not populating data on main entry page on load
#22
> Fix Load Scoresheet Bug

- views/layout.pug
- views/scoresheet.pug
* Fixed bug where scoresheets were submitted by default. 
* Changed autosave frequency to focusout to minimize db usage
> Fix submit bug

- controllers/AuthController.js
> added a login block to user registration

- controllers/AuthController.js
- controllers/ScoresheetController.js
- helpers/errorConstants.js
- migrations/20201024221626-add-descriptors-smoky-brett-spicy.js
- models/Scoresheet.js
- public/javascripts/admin.js
- views/admin.pug
- views/bjcp_modified.pug
- views/profile.pug
- views/register.pug
- views/scoresheet.pug
* Fixed #36 
* Fixed #66 
* Fixed #60 
* Fixed #49 - limited entry text to 6 characters but still allowing alphanumeric
> fixed #36, fixed #66, fixed #60, fixed #49 (sort of)

- views/bjcp_modified.pug
> Fix cicerone display bug and future proof if we null the value later.

- README.md
- package.json
- seeders/20200330053526-default-admin.js
* Updated readme file to include better documentation (fixed #71 )
> updated readme

- views/bjcp_modified.pug
- views/scoresheet.pug
> fixed #89 and fixed #90

- views/scoresheet.pug
Fixed #94 
This is the only thing I can think of right now:
> fixed breaking change where new scoresheets could not be created

- views/bjcp_modified.pug
> updated sliders to use template literals so the linter likes them

- controllers/ScoresheetController.js
- public/javascripts/admin.js
- routes/core.js
- services/pdf.service.js
- views/admin.pug
- views/index.pug
- views/scoresheet.pug
implemented #99 
* added download status endpoint and implemented progress based UI on front end, 
* added download all concat scoresheet and raw data download to admin panel
> Added download progress

- controllers/ScoresheetController.js
- public/javascripts/admin.js
- added logic to prevent unsubmitted flights from being dowloaded in `download all` function
- removed console.log from admin.js
> Minor Bug Fixes for "Download All" Function

- controllers/AuthController.js
- views/profile.pug
* Fixes #129 
* Added `.toLowerCase()` to all email fields
**BONUS**
* Added email verification to email change
* Added email communication preference to update profile form
* Fixed bug where updated email "didn't update" on the update profile form
* Cleaned up unnecessary comments (#53 )
> fixed case sensitive emails

- controllers/ScoresheetController.js
- public/javascripts/admin.js
> fixed issue per description instructions

- public/javascripts/scoresheet.js
- public/stylesheets/style.css
- public/stylesheets/style.styl
- views/scoresheet.pug
* Fixes #130 
* Added summary editable section scores at bottom of scoresheet page
* Scoresheet score border sections turn red when score is "0" to alert user of possible missing data
> added summary score cards to bottom of scoresheet

- public/javascripts/scoresheet.js
* fixes #136 
* Created mapping to allow local TZO in scoresheet to prevent UTC date from being populated
> fixed UTC date issue

- controllers/AuthController.js
- public/javascripts/admin.js
- views/admin.pug
> added ability for admins to manually verify emails and fixed email verification bug

- controllers/AuthController.js
- public/javascripts/scoresheet.js
- views/index.pug
- views/scoresheet.pug
* fixes #100 
* finishes fixing cross platform email verification bug
* minor style updates on scoresheet page
> added next and previous buttons for scoresheet

- controllers/FlightController.js
- controllers/ScoresheetController.js
- public/javascripts/index.js
- public/javascripts/scoresheet.js
- public/javascripts/scoresheet_beer.js
- public/javascripts/scoresheet_mead.js
- services/pdf.service.js
- views/bjcp_modified_mead.pug
- views/index.pug
- views/scoresheet_mead.pug
Added (hack-ish) mead capability by repurposing nonrelevant beer fields in the database and creating digital form and scoresheet template
> feat: added mead capability

- controllers/FlightController.js
- public/javascripts/admin.js
fixed bug that prevented flights from showing up in user modal
> fix: fixed admin panel judge modal

- public/javascripts/admin.js
> fix: fixed bug where flights without ID could not be clicked in admin panel

- migrations/20210314012327-add-competition-info.js
Changed default values for club and comp info
> fix: changed default values

- config/config.json
- controllers/AuthController.js
- droplet-setup.sh
- package.json
- views/scoresheet_mead.pug
* fix #213 
* fixed minor bug on mead scoresheet
* updated droplet deploy script to restart container on bad exit
* suppress sql logs in production (they eat a _lot_ of space on the VM)
> fix: issue with unhelpful password reset message

- views/scoresheet.pug
- views/scoresheet_mead.pug
closes #102 
- Changed the Back to My flight button text to Save and Return to flights.
> Changed "Back to My Flights" button text to "Save and Return to Flights".

- views/scoresheet.pug
- views/scoresheet_mead.pug
closes #111 
- `Finish / Aftertaste` changed to `Finish and Aftertaste`.
> "Finish / Aftertaste" changed to "Finish and Aftertaste".

- views/admin.pug
Signed-off-by: Chinu Anand <chinuanand81@gmail.com>
This PR fixes #205
> Fix typo in output section of admin panel 
